<?php

Class Functions{
    
    private $con;
    public $records;
    public $numlinks;
    public $item_per_page =10;
    
    function __construct(){
        
        require_once dirname(__FILE__).'/connection.php';
        
        
        $database = new Connection();
        
        $this->con = $database->openConnection();
        
        // Require https
//        if ($_SERVER['HTTPS'] != "on") {
//            $url = "https://". $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
//            header("Location: $url");
//            exit;
//        }
    }
        
    
       //count total records
    function countAll($query){
        $stmt = $this->con->prepare($query);
        $stmt->execute();
        return $stmt->rowCount();
    }
    //pagination
    function pagenate($query, $page_number){
        $per_page = $this->item_per_page;
        //$this->item_per_page = $per_page;
        
        $numrecords = $this->countAll($query);
        
        $this->pages = $numrecords;  
        
        $position = (($page_number-1) * $per_page);
        
        $sql_pagination = $this->con->prepare($query." LIMIT ".  $position.",".$per_page);
        //echo "SELECT id,fullname FROM users LIMIT $start,$numperpage";
        $sql_pagination->execute();
        
        return $sql_pagination->fetchAll();
    }
	 
    
    //RETRIEVE SINGLE RECORD
    function retrieveSingle($query){
            $stmt = $this->con->prepare($query);
            $stmt->execute();
            return $stmt->fetch();
            
    }
    
    //RETRIEVE SINGLE RECORD
    function retrieveMany($query){
            $stmt = $this->con->prepare($query);
            $stmt->execute();
            return $stmt->fetchAll();
            
    }
	
     /* function to UPDATE sql data*/
    function updateData($table, $data, $where){
        $cols = array();

        foreach($data as $key=>$val) {
            $cols[] = "$key = '$val'";
        }
        $sql = "UPDATE $table SET " . implode(', ', $cols) . " WHERE $where";
        
        
        $stmt = $this->con->prepare($sql);
        if($stmt->execute()){
            return 1;
        }else{
            return 2;
        }

        
    }
    
     /* function to insert into table */
    function insertData($table, $data) {
        $key = array_keys($data);
        $val = array_values($data);
        $sql = "INSERT INTO $table (" . implode(', ', $key) . ") "
             . "VALUES ('" . implode("', '", $val) . "')";

        $stmt = $this->con->prepare($sql);
        
        if($stmt->execute()){
            return 1;
        }else{
            return 2;
        }
    }
    
    function deleteData($table,$where){
        
        $sql = "DELETE FROM $table WHERE $where";
        
        
        $stmt = $this->con->prepare($sql);
        if($stmt->execute()){
            return 1;
        }else{
            return 2;
        }
    }
    
    
    //firebase function to send to a device
    	function sendNotif($to,$notif){
		$apiKey = 'AAAAr2ZgPDQ:APA91bFueVvFt1D3Hp3XHnIUj0cK-vGr7y3-ynJkgj1iuI8N6LXcrcppup4SiKgKaWCFajkrIdtoQOKXVIdXMK0u-v5Htb44HSuLvDs_2BPiuzKoPsUmaqGeygaRPEoxeqnc6v8tlzQs';

		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		$url = "https://fcm.googleapis.com/fcm/send";
		$fields = json_encode(array('to'=>$to,'data'=>$notif));

		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

		$headers = array();
		$headers[] = 'Authorization: key='.$apiKey;
		$headers[] = 'Content-Type: application/json';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		  //  echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
	}


    
    
    

}

?>